version: "3.9"

services:
  postgres-auth:
    image: postgres:16
    container_name: postgres-auth
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    environment:
      PORT: 4001
      DATABASE_URL: postgresql://auth_user:auth_password@postgres-auth:5432/auth_db
      JWT_SECRET: change_me
      JWT_EXPIRES_IN: 1d
    ports:
      - "4001:4001"
    depends_on:
      - postgres-auth

  vehicle-service:
    build: ./backend/vehicle-service
    container_name: vehicle-service
    environment:
      PORT: 4002
    ports:
      - "4002:4002"

  traffic-service:
    build: ./backend/traffic-service
    container_name: traffic-service
    environment:
      PORT: 4003
    ports:
      - "4003:4003"

  incident-service:
    build: ./backend/incident-service
    container_name: incident-service
    environment:
      PORT: 4004
      NOTIFICATION_SERVICE_URL: http://notification-service:4005
    ports:
      - "4004:4004"

  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    environment:
      PORT: 4005
    ports:
      - "4005:4005"

  graphql-gateway:
    build: ./backend/graphql-gateway
    container_name: graphql-gateway
    environment:
      PORT: 4000
      JWT_SECRET: change_me
      AUTH_SERVICE_URL: http://auth-service:4001/graphql
      VEHICLE_SERVICE_URL: http://vehicle-service:4002/graphql
      TRAFFIC_SERVICE_URL: http://traffic-service:4003/graphql
      INCIDENT_SERVICE_URL: http://incident-service:4004/graphql
      NOTIFICATION_SERVICE_URL: http://notification-service:4005/graphql
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
      - vehicle-service
      - traffic-service
      - incident-service
      - notification-service

  frontend-dashboard:
    build: ./smart-traffic-frontend
    container_name: frontend-dashboard
    environment:
      VITE_INCIDENT_API: http://localhost:4004
      VITE_NOTIFICATION_API: http://localhost:4005
    ports:
      - "5173:5173"
    depends_on:
      - incident-service
      - notification-service

volumes:
  auth_db_data:
